name: 'ffi_universe'
description: 'Standarization FFI will bring support cross platform same style api for boost project'
version: '0.0.7'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/ffi_universe'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  ffi: '^2.1.3'
  js: '^0.7.1'
  http: '^1.3.0'
  meta: '^1.15.0'
  path: '^1.9.0'
  web: '^1.0.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
  general_lib: '^0.0.67'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
project:
  type: 'library'
